CRAWL_TASKS = "crawl_tasks"
CRAWL_RUNS = "crawl_runs"
CRAWL_RUN_DETAIL_TASKS = "crawl_run_detail_tasks"
CRAWL_SCHEDULES = "crawl_schedules"
CRAWL_CONFIG = "crawl_config"
CRAWL_COOKIES_CONFIG = "crawl_cookies_config"
